# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combnGenElemRcpp <- function(xv, nv, kv, chv) {
    .Call('ultraCombo_combnGenElemRcpp', PACKAGE = 'ultraCombo', xv, nv, kv, chv)
}

revCombnGenElemRcpp <- function(xv, nv, chv) {
    .Call('ultraCombo_revCombnGenElemRcpp', PACKAGE = 'ultraCombo', xv, nv, chv)
}

